## Colors configuration
colors:
  # Default colors
  primary:
    background: '#1e222a'
    foreground: '#c8ccd4'

  # Normal colors
  normal:
    black:   '#282c34'
    red:     '#e06c75'
    green:   '#98c379'
    yellow:  '#e5c07b'
    blue:    '#61afef'
    magenta: '#c678dd'
    cyan:    '#56b6c2'
    white:   '#abb2bf'

  # Bright colors
  bright:
    black:   '#545862'
    red:     '#e06c75'
    green:   '#98c379'
    yellow:  '#e5c07b'
    blue:    '#61afef'
    magenta: '#c678dd'
    cyan:    '#56b6c2'
    white:   '#c8ccd4'
