## Colors configuration
colors:
  # Default colors
  primary:
    background: '#000b1e'
    foreground: '#0abdc6'

  # Normal colors
  normal:
    black:   '#FF2079'
    red:     '#221ae8'
    green:   '#FF0008'
    yellow:  '#F20361'
    blue:    '#DD2BF7'
    magenta: '#00B4FF'
    cyan:    '#FA00FF'
    white:   '#FFFD01'

  # Bright colors
  bright:
    black:   '#ed005f'
    red:     '#070283'
    green:   '#9100a6'
    yellow:  '#ff0064'
    blue:    '#0254C1'
    magenta: '#00FE66'
    cyan:    '#32FF00'
    white:   '#C9FA00'
