## Colors configuration
colors:
  # Default colors
  primary:
    background: '#181f21'
    foreground: '#dadada'

  # Normal colors
  normal:
    black:   '#22292b'
    red:     '#e06e6e'
    green:   '#8ccf7e'
    yellow:  '#e5c76b'
    blue:    '#67b0e8'
    magenta: '#c47fd5'
    cyan:    '#6da4cd'
    white:   '#b3b9b8'

  # Bright colors
  bright:
    black:   '#3b4244'
    red:     '#ef7d7d'
    green:   '#9bdead'
    yellow:  '#f4d67a'
    blue:    '#6cb5ed'
    magenta: '#ce89df'
    cyan:    '#67cbe7'
    white:   '#bdc3c2'
